### ISSUE TITLE
What about static methods?

### ISSUE THREAD

**Issue by asd-and-Rizzo** [BrunoJuchli/StaticProxy.Fody#3]
E.g.
```
using System;
namespace Service
{
    public class MyClass
    {
        public static void WriteLine()
        {
            Console.WriteLine("Real class did this");
        }
    }
}
```

**Comment by asd-and-Rizzo** [comment]
StaticProxy better to support static classes because of name:)

Right now found https://github.com/Fody/Ionad

**Comment by BrunoJuchli** [comment]
Yes you're right you can use Ionad for that. Depending on your usecase you could also use [MethodDecorator](https://github.com/Fody/MethodDecorator).

I currently don't plan to add support for static methods. The way which StaticProxy.Fody works would make it very, very difficult to do so.

The only reason to use StaticProxy.Fody instead of Castle.DynamicProxy, Linfu Proxy or any other dynamic proxy is to use proxying on platforms which don't allow runtime-weaving (IL-Emit). For example IPhone's.
However i have to admit that the project is currently not fully Xamarin compatible. Due to lack of interest of other parties i have suspended further development. If there would be someone wanting to use it and willing to test it, i would gladly finish the work.

Regarding the name: You're right it is somewhat confusing. I chose the name to clearly differentiate from DynamicProxy (which is dynamically created during compile time). But still you're right maybe i should look for a better name... what do you think about CompileProxy, WovenProxy? Do you have any suggestions? It should clearly indicate that it's not done "dynamically" during runtime...
